### PR TITLE
Chore Fix types in jest, bump jest packages

### PR DESCRIPTION
**Pull request by TKDBB84**
Newer version of discord has an updated client type, that is not compatible with the older version, with 13.7+ i recommend a new minor version release.

Chores: 
- [x] Bumps Jest to latest
- [x] Corrects minor items in package.json
- [x] corrects discord types for tests

### CODE REVIEW

**Comment by TKDBB84** [comment]
Hey @robertsmieja curious if you'd be interested in merge this and publishing a new minor version.  I can clean up the package conflicts if needed.

**Comment by robertsmieja** [comment]
Yes, I just have been busy with work and neglected this repo and GitHub notifications.

This package is overdue for minor updates and fixes.

**Comment by robertsmieja** [comment]
In the future, if I'm not responsive on GitHub, you can message me on Keybase - https://keybase.io/robertsmieja

**Comment by TKDBB84** [comment]
Thanks Robert, it wasn't urgent. I appreciate the updates and the library you maintain here. 👍

**Comment by robertsmieja** [comment]
I'm glad someone else finds my code useful. :)

**Pull request merged**
